/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedCadastroRouteImport } from './routes/_authenticated/cadastro'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated/avisos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedAdminAdminSolicitarUtilizadoresRouteImport } from './routes/_authenticated/_admin/admin_.solicitar-utilizadores'
import { Route as AuthenticatedAdminAdminColaboradoresRouteImport } from './routes/_authenticated/_admin/admin_.colaboradores'
import { Route as AuthenticatedAdminAdminColaboradoresIdRouteImport } from './routes/_authenticated/_admin/admin_.colaboradores_.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCadastroRoute = AuthenticatedCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdminSolicitarUtilizadoresRoute =
  AuthenticatedAdminAdminSolicitarUtilizadoresRouteImport.update({
    id: '/admin_/solicitar-utilizadores',
    path: '/admin/solicitar-utilizadores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminColaboradoresRoute =
  AuthenticatedAdminAdminColaboradoresRouteImport.update({
    id: '/admin_/colaboradores',
    path: '/admin/colaboradores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminColaboradoresIdRoute =
  AuthenticatedAdminAdminColaboradoresIdRouteImport.update({
    id: '/admin_/colaboradores_/$id',
    path: '/admin/colaboradores/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/cadastro': typeof AuthenticatedCadastroRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/admin/colaboradores': typeof AuthenticatedAdminAdminColaboradoresRoute
  '/admin/solicitar-utilizadores': typeof AuthenticatedAdminAdminSolicitarUtilizadoresRoute
  '/admin/colaboradores/$id': typeof AuthenticatedAdminAdminColaboradoresIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/cadastro': typeof AuthenticatedCadastroRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/admin/colaboradores': typeof AuthenticatedAdminAdminColaboradoresRoute
  '/admin/solicitar-utilizadores': typeof AuthenticatedAdminAdminSolicitarUtilizadoresRoute
  '/admin/colaboradores/$id': typeof AuthenticatedAdminAdminColaboradoresIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/cadastro': typeof AuthenticatedCadastroRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRoute
  '/_authenticated/_admin/admin_/colaboradores': typeof AuthenticatedAdminAdminColaboradoresRoute
  '/_authenticated/_admin/admin_/solicitar-utilizadores': typeof AuthenticatedAdminAdminSolicitarUtilizadoresRoute
  '/_authenticated/_admin/admin_/colaboradores_/$id': typeof AuthenticatedAdminAdminColaboradoresIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/esqueci-senha'
    | '/login'
    | '/primeiro-acesso'
    | '/reset-password'
    | '/avisos'
    | '/cadastro'
    | '/inicio'
    | '/admin'
    | '/admin/colaboradores'
    | '/admin/solicitar-utilizadores'
    | '/admin/colaboradores/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/esqueci-senha'
    | '/login'
    | '/primeiro-acesso'
    | '/reset-password'
    | '/avisos'
    | '/cadastro'
    | '/inicio'
    | '/admin'
    | '/admin/colaboradores'
    | '/admin/solicitar-utilizadores'
    | '/admin/colaboradores/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/esqueci-senha'
    | '/login'
    | '/primeiro-acesso'
    | '/reset-password'
    | '/_authenticated/_admin'
    | '/_authenticated/avisos'
    | '/_authenticated/cadastro'
    | '/_authenticated/inicio'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/_admin/admin_/colaboradores'
    | '/_authenticated/_admin/admin_/solicitar-utilizadores'
    | '/_authenticated/_admin/admin_/colaboradores_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro': {
      id: '/_authenticated/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof AuthenticatedCadastroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin_/solicitar-utilizadores': {
      id: '/_authenticated/_admin/admin_/solicitar-utilizadores'
      path: '/admin/solicitar-utilizadores'
      fullPath: '/admin/solicitar-utilizadores'
      preLoaderRoute: typeof AuthenticatedAdminAdminSolicitarUtilizadoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin_/colaboradores': {
      id: '/_authenticated/_admin/admin_/colaboradores'
      path: '/admin/colaboradores'
      fullPath: '/admin/colaboradores'
      preLoaderRoute: typeof AuthenticatedAdminAdminColaboradoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin_/colaboradores_/$id': {
      id: '/_authenticated/_admin/admin_/colaboradores_/$id'
      path: '/admin/colaboradores/$id'
      fullPath: '/admin/colaboradores/$id'
      preLoaderRoute: typeof AuthenticatedAdminAdminColaboradoresIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
  AuthenticatedAdminAdminColaboradoresRoute: typeof AuthenticatedAdminAdminColaboradoresRoute
  AuthenticatedAdminAdminSolicitarUtilizadoresRoute: typeof AuthenticatedAdminAdminSolicitarUtilizadoresRoute
  AuthenticatedAdminAdminColaboradoresIdRoute: typeof AuthenticatedAdminAdminColaboradoresIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
  AuthenticatedAdminAdminColaboradoresRoute:
    AuthenticatedAdminAdminColaboradoresRoute,
  AuthenticatedAdminAdminSolicitarUtilizadoresRoute:
    AuthenticatedAdminAdminSolicitarUtilizadoresRoute,
  AuthenticatedAdminAdminColaboradoresIdRoute:
    AuthenticatedAdminAdminColaboradoresIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedCadastroRoute: typeof AuthenticatedCadastroRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedCadastroRoute: AuthenticatedCadastroRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
